version: 0.2

env:
  git-credential-helper: yes

proxy:
    upload-artifacts: yes
    logs: yes
            
phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - npm run build
      - npm run deploy
